#!/bin/sh
. './scripts/build'
. './scripts/copy_dist'
. './scripts/copy_bundle'
. './scripts/copy_packed'

build_page() {
  local source=$1
  local dest=$2
  local library_name=$3
  local npm_build_targets=$4
  local bundle=$5

  build $source "$npm_build_targets"
  mkdir -p $dest/dist
  copy_dist $source/dist $dest/dist
  if [ "$bundle" != "" ]; then
    copy_bundle $source/dist/$bundle $dest
  fi

  copy_packed $source/$library_name*.tgz $dest/$library_name.tgz
}
