#!/bin/sh
. './scripts/build'
. './scripts/copy_dist'
. './scripts/copy_bundle'
. './scripts/copy_packed'

build_page() {
  local source=$1
  local dest=$2
  local library_name=$3
  local npm_build_targets=$4
  local bundle=$5

  if [ -z $bundle]; then
    bundle="$library_name.js"
  fi

  build $source "$npm_build_targets"
  mkdir $dest/dist
  copy_dist $source/dist $dest/dist
  copy_bundle $source/dist/$bundle $dest
  copy_packed $source/$library_name*.tgz $dest/$library_name.tgz
}
