#!/bin/sh

clone() {
  local working_dir=$1
  local repo_url=$2
  local branch=$3

  local tmp_dir="$branch-tmp"
  (cd $working_dir && git clone $repo_url --branch $branch $tmp_dir) && echo "$working_dir/$tmp_dir"
}