#!/bin/sh

copy_dist() {
  local source=$(append_slash $1)
  local dest=$(append_slash $2)

  cp -r $source $dest
}

append_slash() {
  local value=$1

  if [ $(grep -e '\/$' <<< "$value") ]; then
    echo $value
  else
    echo $value/
  fi
}